CREATE TABLE users (
	id UUID PRIMARY KEY,
	email TEXT UNIQUE NOT NULL,
	password TEXT NOT NULL,
	dark_mode BOOLEAN NOT NULL DEFAULT FALSE,
	updated_on DATE NOT NULL DEFAULT CURRENT_DATE
);

CREATE TABLE atoms (
	id UUID PRIMARY KEY,
	user_id UUID NOT NULL,
	title TEXT NOT NULL,
	time_initial INTERVAL NOT NULL,
	time_current INTERVAL NOT NULL
);

CREATE TABLE histories (
	id UUID PRIMARY KEY,
	user_id UUID NOT NULL,
	date DATE NOT NULL,
	completed INTEGER NOT NULL,
	total INTEGER NOT NULL
);
